/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DOAN;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;


/**
 *
 * @author Administrator
 */
public class FormDN extends javax.swing.JFrame {

    /**
     * Creates new form FormDN
     */
    public FormDN() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=QLGiayDep;user=sa;password=123456;"+"encrypt=true;trustServerCertificate=true;sslProtocol=TLSv1.2;";
    String driver="com.microsoft.sqlserver.jdbc.SQLServerDriver";
    Statement st;
    ResultSet rs;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtdn = new javax.swing.JTextField();
        btndn = new javax.swing.JButton();
        btndk = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jfpass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        txtdn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdnActionPerformed(evt);
            }
        });

        btndn.setText("Dang Nhap");
        btndn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndnActionPerformed(evt);
            }
        });

        btndk.setText("Dang Ky");
        btndk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndkActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("LOGIN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtdn)
                            .addComponent(jfpass, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btndn)
                        .addGap(62, 62, 62)
                        .addComponent(btndk))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel3)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtdn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jfpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndn)
                    .addComponent(btndk))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndkActionPerformed
        ThemTaiKhoan l = new ThemTaiKhoan();
        l.setVisible(true);
        this.setVisible(false);
        l.setLocationRelativeTo(null);
    }//GEN-LAST:event_btndkActionPerformed

    private void btndnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndnActionPerformed
        try{
            Class.forName(driver);
            Connection con = DriverManager.getConnection(connectionUrl);
            String sql="select * from ACCOUNT where USERNAME=? and PASSWORD=?";//CAU TRUY VAN DEN SQL
            PreparedStatement ps= con.prepareCall(sql);//cho phep chi dinh tham so dau vao khi chay
            ps.setString(1,txtdn.getText());
            ps.setString(2,jfpass.getText());
            rs = ps.executeQuery();//executeQuery tra ve mot doi tuong resultset khi thuc thi cau lenh select
            
            if(txtdn.getText().equals("")||jfpass.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "chua nhap user va pass");
            }
            else if(rs.next()){
                
                JOptionPane.showMessageDialog(this, "Dang nhap thanh cong");
                if(rs.getString(5).equals("Admin")){
                    GiaoDienChinh l = new GiaoDienChinh();
                    l.setVisible(true);
                    this.setVisible(false);
                    l.setLocationRelativeTo(null);
                }
                if(rs.getString(5).endsWith("Nhap Kho")){
                    NhapHangView_1 l = new NhapHangView_1();
                    l.setVisible(true);
                    this.setVisible(false);
                    l.setLocationRelativeTo(null);
                }
                 if(rs.getString(5).endsWith("Xuat Kho")){
                    XuatHangView_1 l = new XuatHangView_1();
                    l.setVisible(true);
                    this.setVisible(false);
                    l.setLocationRelativeTo(null);
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Dang nhap that bai");
            }
            
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_btndnActionPerformed

    private void txtdnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndk;
    private javax.swing.JButton btndn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jfpass;
    private javax.swing.JTextField txtdn;
    // End of variables declaration//GEN-END:variables
}
