/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DOAN;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Administrator
 */
public class KhoHang extends javax.swing.JFrame {
    DefaultTableModel model; 
   /**
  
    /**
     * Creates new form KhoHang
     */
    public KhoHang() {
        initComponents();
        String[] header = {"Mã hàng", "Size", "Màu sắc", "Hãng sản xuất", "Giá", "Loại hàng", "Số lượng"};
        model=new DefaultTableModel(header,0);
        tblKhoGiayDep.setModel(model);
        initLoadDataToJtable();
        this.setLocationRelativeTo(null);
    }
    public void initLoadDataToJtable(){
        
        model.setRowCount(0);//xoa toan bo cac dong hien ton tai tren ban 
        String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=QLGiayDep;user=sa;password=123456;"+"encrypt=true;trustServerCertificate=true;sslProtocol=TLSv1.2;";

        try  {
            Connection con = DriverManager.getConnection(connectionUrl); 
            Statement stmt = con.createStatement();
            String SQL = "SELECT * FROM KhoGiayDep";// dat cac chuoi leng vao bien SQL
            ResultSet rs = stmt.executeQuery(SQL);//goi rs truy van vao database

            // Iterate through the data in the result set and display it.
            while (rs.next()) {
                String[] row= new String[]{rs.getString("ComodityCode"),
                                           rs.getString("Size"),
                                           rs.getString("Color"),
                                           rs.getString("Manufacturer"),
                                           rs.getString("Price"),
                                           rs.getString("Comodities"),
                                           rs.getString("Quantity")
                        
                };

                model.addRow(row);
            }
            con.close();//dong cac ket noi
            rs.close();
            stmt.close();
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            e.printStackTrace();
        }
        
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhoGiayDep = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        txtFind = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font(".VnArial", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THONG TIN CAC SAN PHAM");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tblKhoGiayDep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ComodityCode", "Size", "Color", "Manufacturer", "Price", "Comodities", "Quantity"
            }
        ));
        tblKhoGiayDep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhoGiayDepMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhoGiayDep);
        if (tblKhoGiayDep.getColumnModel().getColumnCount() > 0) {
            tblKhoGiayDep.getColumnModel().getColumn(0).setHeaderValue("ComodityCode");
            tblKhoGiayDep.getColumnModel().getColumn(1).setHeaderValue("Size");
            tblKhoGiayDep.getColumnModel().getColumn(2).setHeaderValue("Color");
            tblKhoGiayDep.getColumnModel().getColumn(3).setHeaderValue("Manufacturer");
            tblKhoGiayDep.getColumnModel().getColumn(4).setHeaderValue("Price");
            tblKhoGiayDep.getColumnModel().getColumn(5).setHeaderValue("Comodities");
            tblKhoGiayDep.getColumnModel().getColumn(6).setHeaderValue("Quantity");
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setText("Quay lai man hinh chinh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnEdit.setText("Sua");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        txtFind.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindActionPerformed(evt);
            }
        });

        btnFind.setText("Tim Kiem");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnFind)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit)
                        .addGap(40, 40, 40)
                        .addComponent(jButton2))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind)
                    .addComponent(btnEdit)
                    .addComponent(jButton2)
                    .addComponent(btnRefresh))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFindActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        //find=txtFind.getText();
        model.setRowCount(0);
        String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=QLGiayDep;user=sa;password=123456;"+"encrypt=true;trustServerCertificate=true;sslProtocol=TLSv1.2;";

        try  {
            Connection con = DriverManager.getConnection(connectionUrl); 
            
            String SQL = "SELECT * FROM KhoGiayDep "
                    + " WHERE ComodityCode like '%"+txtFind.getText()+"%' or Size like '%"+txtFind.getText()+"%' or Color like '%"+txtFind.getText()+"%' or Manufacturer like '%"+txtFind.getText()+"%' or Price like '%"+txtFind.getText()+"%' or Comodities like '%"+txtFind.getText()+"%' or Quantity like '%"+txtFind.getText()+"%' ";// dat cac chuoi leng vao bien SQL
            PreparedStatement psmt = con.prepareStatement(SQL);
            
            
            ResultSet rs = psmt.executeQuery();//goi rs truy van vao database

            // Iterate through the data in the result set and display it.
            while (rs.next()) {
                String[] row= new String[]{rs.getString("ComodityCode"),
                                           rs.getString("Size"),
                                           rs.getString("Color"),
                                           rs.getString("Manufacturer"),
                                           rs.getString("Price"),
                                           rs.getString("Comodities"),
                                           rs.getString("Quantity")
                        
                };

                model.addRow(row);
            }
            con.close();//dong cac ket noi
            rs.close();
            psmt.close();
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        SuaThongTinKho f1 = new SuaThongTinKho();
        String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=QLGiayDep;user=sa;password=123456;"+"encrypt=true;trustServerCertificate=true;sslProtocol=TLSv1.2;";

        try{
          Connection con = DriverManager.getConnection(connectionUrl); 
                String SQL = "SELECT * FROM KhoGiayDep where ComodityCode=?";// dat cac chuoi leng vao bien SQL
                PreparedStatement psmt = con.prepareStatement(SQL);
                psmt.setString(1, txtFind.getText());
                ResultSet rs = psmt.executeQuery();//dung rs de truy xuat lai ket qua truy van         
                
                if(rs.next()){//neu ma hang da ton tai trong kho thi chi cho nguoi dung sua so luong hang nhap vao khong duoc sua thong tin co san cua hang
                    SuaThongTinKho f2 = new SuaThongTinKho();
                    f2.nhanthongtin(rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7));
                    f2.setVisible(true);
                    f2.setLocationRelativeTo(null);
                }  
        }
        catch (Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void tblKhoGiayDepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhoGiayDepMouseClicked
        // TODO add your handling code here:
        int selectedrow = tblKhoGiayDep.getSelectedRow();
        
        txtFind.setText((String) tblKhoGiayDep.getValueAt(selectedrow, 0));
    }//GEN-LAST:event_tblKhoGiayDepMouseClicked

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        initLoadDataToJtable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       GiaoDienChinh gd = new GiaoDienChinh();
       gd.setVisible(true);
       gd.setLocationRelativeTo(null);
       this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhoHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKhoGiayDep;
    private javax.swing.JTextField txtFind;
    // End of variables declaration//GEN-END:variables

    
}
